
# Location of the AR include files and the AR library
ARINCLUDE	= ../include
ARLIB		= ../lib

# Name of GP library.  Change '.a' to '.so' if you want to use dynamic
# libraries, and change the archive command in src/Makefile as well.
ARLIBFILE = $(ARLIB)/libar.a

# Compiler flags.  Use -O to optimise
OVERALLCPPFLAGS	= -g

# Linker flags.
OVERALLLDFLAGS	= 

# C++ compiler
#CCC		= CC
CCC		= g++

# Archive command
AR		= ar

# Ranlib command
RANLIB		= ranlib

# Install command and installation directory
INSTALL		= install
INSTALLDIR	= /usr/local
